#!/bin/sh

filestart="$HOME/Pictures/screenshot"
number=0
while test -e "$filestart$number.png"; do
	(( ++number))
done

fname="$filestart$number.png"

if [ $1 = "full" ]; then
    grim $fname
else
    grim -g "$(slurp)" $fname
fi
